### ISSUE TITLE
🎨 CLUB

### ISSUE THREAD

**Issue by 7alip** [wsvvrijheid/wsvvrijheid#26]
### Describe the feature you'd like to request

We would like to have a club page on which any authenticated user can post his/her arts. The page will look like this social media project https://github.com/adrianhajdin/project_shareme_social_media.

This feature has three parts and some parts will probably be created in separated branches/issues/PRs.

1. Backend data modeling
2. Frontend
3. Authentication

## 1. Backend

Extend art and artist models.

## 2. Frontend

- [x] **List arts in `/club` page**
  - [x] Add masonry grid #27 
  - [x] Add filtering by category feature in sidebar #28 
  - [x] Add pagination #29 
- [ ] **Create SSG/ISR single art page `/club/art/:id`** 
  - [x] Show details (description or story) of the art #30 
  - [x] Add `Like` button #31 
  - [x] Add comment feature #32  
- [ ] **Create SSG/ISR singe artist page `/club/artist/:username`**
  - [x] Show details of the artist #95 
  - [x] List the artist's arts #34 

## 3. Authentication

Authentication is actually not specific for this feature. We will be using login/signup for also **Application for Competitions**.

> TODO: Explain steps

### Describe the solution you'd like

> TODO: Describe

**Comment by 7alip** [comment]
### Fetching Data

By default Strapi doesn't provide populated data of a relation in an item.
If we want to display arts, artists of each art and name/avatar of the artist in a single post card, in our request we need to provide fields to be populated.

Art model:

```ts
type Art = {
  title: string
  slug: string
  description: string
  content: string
  likes: number
  images: File[] // relation
  artist: Artist // Relation
  categories: Category[] Relation
}

type Artist = {
  arts: Art[]
  volunteer: Volunteer
}

type Volunteer = {
  username: string
  name: string
  avatar: File
  ...
}
```


1. `populate="*"` gets all `first-level` relational data which means you will not see the data for second/third nested field.
2. In order to get `art.artist.volunteer.avatar` we need to provide the following query to `request` function:

```js
request({
  url: "api/arts",
  populate: ["artist.volunteer.avatar"]
})
``` 

**Flatten Strapi Response**

Strapi v4 responses look a bit complex. We have `transform-strapi-data` utility function to flatten this complex structure.
We return the transformed response in `request` function You can compare the following results what the transformation looks like:

```js
// Strapi Response
{
  title: "A",
  author: {
    data: {
      id: 1,
      attributes: {
        volunteer: {
          data: {
            attributes: {
              name: "B",
              avatar: {
                data: {
                  id: 2,
                  attributes: {
                    url: "..."
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}

// Simplified Response
{
  title: "A",
  author: {
    id: 1,
    volunteer: {
      name: "B",
      avatar: {
        url
      }
    }
  }
}
```
